# Generated by Django 4.0.5 on 2022-07-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default_product.pk', null=True, upload_to=''),
        ),
    ]
