# Generated by Django 4.0.5 on 2022-07-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_thumb'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='shop_brands',
        ),
    ]
