# Generated by Django 4.0.5 on 2022-07-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_brand_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='shop_categories',
        ),
    ]
